### ISSUE TITLE
Release on Maven Central

### ISSUE THREAD

**Issue by Fox32** [opentracing-contrib/java-aws-sdk#15]
The latest release after 0.1.1 (e.g. 0.1.5) [are not available at Maven Central](https://mvnrepository.com/artifact/io.opentracing.contrib/opentracing-aws-sdk). Can you upload them / fix the upload process?

**Comment by malafeev** [comment]
artifact id was renamed, please check:
- https://mvnrepository.com/artifact/io.opentracing.contrib/opentracing-aws-sdk-1
- https://mvnrepository.com/artifact/io.opentracing.contrib/opentracing-aws-sdk-2

**Comment by Fox32** [comment]
Sorry, didn't noticed that. Thanks!
