### ISSUE TITLE
Operation contains service name and Component just java_aws_sdk

### ISSUE THREAD

**Issue by danielrohe** [opentracing-contrib/java-aws-sdk#6]
All spans with traces for the AWS SDK have the AWS service name as operation and the component java_aws_sdk and a special tag operation_name that contains the name of the AWS SDK operation.

Wouldn't it be more readable to store the service name as component and the name of the AWS SDK operation as operation?

**Comment by malafeev** [comment]
For example:
"component" -> "java-aws-sdk"
"operationName" -> "AmazonDynamoDBv2"
"original_request" -> "CreateTableRequest"

@danielrohe could you clarify what do you propose to change on the example above?

**Comment by danielrohe** [comment]
I think it would be better to have the following:

"component" -> "AmazonDynamoDBv2"
"operationName" -> "CreateTableRequest"

For me this is more intuitive as the operationName tag then contains the AWS operation and the component tag contains the name of the AWS service.

**Comment by danielrohe** [comment]
I think it would be better to have the following:

"component" -> "AmazonDynamoDBv2"
"operationName" -> "CreateTableRequest"

For me this is more intuitive as the operationName tag then contains the AWS operation and the component tag contains the name of the AWS service.

**Comment by malafeev** [comment]
- from other instrumentation "component" is a high level name like "java-jms", "java-jdbc" etc.
- use "original_request" as "operationName"  probably makes sense but not 100% sure that   "original_request" is always looks like operation 
cc @tedsuo

**Comment by danielrohe** [comment]
As what I know about the SDK the original_request class name corresponds with the AWS CLI operation which can be done and also the e.g. on cli "aws s3 put" will be "PutObjectRequest" on AWS Java SDK.

I also thought about whether e.g. AmazonDynamoDBv2 or AmazonS3 is enough for component name, I also had java-aws-sdk::AmazonDynamoDBv2 in mind. The main point I like the service name for component (e.g. AmazonDynamoDBv2 or AmazonS3) is because in my view the AWS Java SDK is a collection of components (it even has a jar per component) where each component is a client to a specific AWS service where the service name identifies the AWS service that is called.

**Comment by tedsuo** [comment]
I agree that what you are proposing makes better sense than what is currently set. This is due to the aws sdk being a very generic piece of code.  As there may be aws operations which are repeated across multiple aws services, indicating the service being targeted as a tag is necessary so that traces can be indexed by service. 

Normally “component” points to the codebase/library doing the work. We could add an additional “aws_service” tag to set the service type, and move the “original_request” tag to operation name. That would look logical to me. 

Comments? Objections?

**Comment by danielrohe** [comment]
Actually you're right its more logical to have component "aws-java-sdk", store the class name as operation name and write the service name into another tag like "aws_service". Because this somehow follows the semantic conventions defined by opentracing (https://opentracing.io/specification/conventions/). Having this in mind i would propose to not use the tag "aws_service" but instead write the service name into the tag "peer.service".

What is your opinion?

**Comment by malafeev** [comment]
thanks @danielrohe 
I will release new version during 24 hours.
